packages:
  - 'packages/react-ui'
  - 'packages/landing'
  - 'packages/build'
  - 'packages/functions'

catalog:
  # Build tools
  vite: ^5.4.19
  vitest: ^3.1.4
  typescript: ^5.2.2
  'vite-plugin-dts': ^4.5.4
  tsx: ^4.7.0

  # React
  react: ^18.2.0
  'react-dom': ^18.2.0
  '@types/react': ^18.2.37
  '@types/react-dom': ^18.2.15
  '@vitejs/plugin-react': ^4.3.4

  # ESLint
  eslint: ^9.27.0
  '@eslint/js': ^9.27.0
  '@typescript-eslint/eslint-plugin': ^8.32.1
  '@typescript-eslint/parser': ^8.32.1
  'eslint-plugin-react-hooks': ^5.2.0
  'eslint-plugin-react-refresh': ^0.4.9

  # Styling
  tailwindcss: ^3.4.1
  postcss: ^8.4.35
  autoprefixer: ^10.4.17

  # Development tools
  'live-server': ^1.2.2
  'chokidar-cli': ^3.0.0
  chokidar: ^3.6.0

  # Utilities
  '@types/node': ^20.9.0
  concurrently: ^8.2.2
  jsdom: ^26.1.0
